name: Deploy Campus-Ease

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies for Frontend
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        env:
          API_URL: https://${{ secrets.DOMAIN_NAME }}/api
        run: |
          cd frontend
          # Update API URLs before build
          find src -type f -name "*.js*" -exec sed -i 's|https://campus-ease-backend.onrender.com|https://${{ secrets.DOMAIN_NAME }}/api|g' {} \;
          npm run build

      - name: Install dependencies for Admin
        run: |
          cd Admin
          npm install

      - name: Build Admin
        env:
          API_URL: https://${{ secrets.DOMAIN_NAME }}/api
        run: |
          cd Admin
          # Update API URLs before build
          find src -type f -name "*.js*" -exec sed -i 's|https://campus-ease-backend.onrender.com|https://${{ secrets.DOMAIN_NAME }}/api|g' {} \;
          npm run build

      - name: Install Backend dependencies
        run: |
          cd Backend
          npm install

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        run: |
          # Create required directories on the VM
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "mkdir -p ~/Campus-Ease/frontend ~/Campus-Ease/Admin ~/Campus-Ease/Backend"
          
          # Copy files to VM
          scp -r frontend/dist/* ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }}:~/Campus-Ease/frontend/dist/
          scp -r Admin/dist/* ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }}:~/Campus-Ease/Admin/dist/
          scp -r Backend/* ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }}:~/Campus-Ease/Backend/
          
          # Execute deployment script
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "export DATABASE_URL='$DATABASE_URL' && export JWT_SECRET='$JWT_SECRET' && export DOMAIN_NAME='$DOMAIN_NAME' && cd ~/Campus-Ease && bash ./deploy.sh"