name: Deploy CampusEase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          EC2_HOST: 54.81.119.40
          EC2_USER: ubuntu
        run: |
          echo "$SSH_PRIVATE_KEY" > campus-ease.pem
          chmod 600 campus-ease.pem
          ssh -i campus-ease.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            # Clone repo if not already present
            if [ ! -d "/home/ubuntu/Campus-Ease" ]; then
              git clone git@github.com:Vinayak2k03/Campus-Ease.git /home/ubuntu/Campus-Ease
            fi
            
            cd /home/ubuntu/Campus-Ease
            git pull origin main

            # Deploy Backend
            cd backend
            npm install
            pm2 restart all

            # Deploy Frontend
            cd ../frontend
            npm install
            npm run build
            sudo cp -r build/* /var/www/campusease-frontend

            # Deploy Admin Panel
            cd ../admin
            npm install
            npm run build
            sudo cp -r build/* /var/www/campusease-admin

            # Restart Nginx
            sudo systemctl restart nginx
          EOF
